version: '3.8'

services:
  mariadb:
    image: 'mariadb:10.4'
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: space
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MARIADB_ROOT_PASSWORD: symfony
    ports:
      - '3306:3306'
    volumes:
      - ./mariadb:/var/lib/mariadb
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - mariadb
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mariadb

networks:
  symfony:
